### ISSUE TITLE
TODO: VR-UI System

### ISSUE THREAD

**Issue by IJEMIN** [IJEMIN/Unity-OpenVR-Shooter-Template#2]
- [x] VRInteractable
- [x] VREyeRaycaster
- [x] Let VRInputController directly know game logic or not?
- [x] VRInputController provide static Input check functions VS one VRInputController per one interact object?
- [x] Use UnityEvent for beginner? or Use action for clean structure?

**Comment by IJEMIN** [comment]
Done with dcd644a8524ef036f7d4c2a9ddbb13a0562a1444
